### ISSUE TITLE
请求解惑

### ISSUE THREAD

**Issue by PingmengWocha** [Anyuoo/Mybatis-Design#1]
在setMappers方法那边视频是使用的this.mappers.putAll(mappers)来赋值的（我确实是没有运行成功），为什么你在那边就直接赋值Mappers = mappers，这样后一次执行的结果不会覆盖前一此执行此方法的结果吗（我确实用此方法运行成功了），现在一头雾水

**Comment by Anyuoo** [comment]
我重新改了一下，你可以看看。用Mappers.putAll（mappers）报错原因：,第一次Mappers对象是null，用putAll就会报错空指针异常，debug跟踪方法执行并没有注入mappers，只有在Mappers对象不为null才能使用putAll方法，所以第一次初始化直接赋值就可以了。正是我的解决方案，你可以看看
